In [2]:
import pandas as pd
import numpy as np
import json

In [7]:
airbnb_calendar = pd.read_csv(r'http://data.insideairbnb.com/spain/catalonia/barcelona/2018-11-07/data/calendar.csv.gz')

In [8]:
airbnb_calendar.shape

(6696290, 4)

In [9]:
airbnb_calendar.head(20)

    listing_id        date available   price
0        74562  2019-11-06         t  $60.00
1        74562  2019-11-05         t  $60.00
2        74562  2019-11-04         t  $60.00
3        74562  2019-11-03         t  $60.00
4        74562  2019-11-02         t  $65.00
5        74562  2019-11-01         t  $65.00
6        74562  2019-10-31         t  $60.00
7        74562  2019-10-30         t  $60.00
8        74562  2019-10-29         t  $60.00
9        74562  2019-10-28         t  $60.00
10       74562  2019-10-27         t  $60.00
11       74562  2019-10-26         t  $65.00
12       74562  2019-10-25         t  $65.00
13       74562  2019-10-24         t  $60.00
14       74562  2019-10-23         t  $60.00
15       74562  2019-10-22         t  $60.00
16       74562  2019-10-21         t  $60.00
17       74562  2019-10-20         t  $60.00
18       74562  2019-10-19         t  $65.00
19       74562  2019-10-18         t  $65.00

In [11]:
airbnb_listings_simple_2018 = pd.read_csv(r'http://data.insideairbnb.com/spain/catalonia/barcelona/2018-11-07/visualisations/listings.csv')

In [ ]:
airbnb_listings_simple_2018.shape

In [ ]:
airbnb_listings_simple_2018.loc[airbnb_listings_simple_2018['id'] == 21416408]

## Merge Calendar & Listing on listing id

In [12]:
table_neighborhood_raw = pd.DataFrame.merge(airbnb_calendar, airbnb_listings_simple_2018, left_on = 'listing_id', right_on = 'id')

In [13]:
table_neighborhood_raw.shape

(6696290, 20)

In [14]:
table_neighborhoods = table_neighborhood_raw[['listing_id', 'date', 'available', 'price_x',  'neighbourhood_group','latitude', 'longitude', 'room_type']]

In [15]:
table_neighborhoods

,listing_id,date,available,price_x,neighbourhood_group,latitude,longitude,room_type
0,74562,2019-11-06,t,$60.00,Ciutat Vella,41.382550,2.168365,Private room
1,74562,2019-11-05,t,$60.00,Ciutat Vella,41.382550,2.168365,Private room
2,74562,2019-11-04,t,$60.00,Ciutat Vella,41.382550,2.168365,Private room
3,74562,2019-11-03,t,$60.00,Ciutat Vella,41.382550,2.168365,Private room
4,74562,2019-11-02,t,$65.00,Ciutat Vella,41.382550,2.168365,Private room
...,...,...,...,...,...,...,...,...
6696285,29529267,2018-11-11,f,NaN,Eixample,41.388619,2.168970,Entire home/apt
6696286,29529267,2018-11-10,f,NaN,Eixample,41.388619,2.168970,Entire home/apt
6696287,29529267,2018-11-09,f,NaN,Eixample,41.388619,2.168970,Entire home/apt
6696288,29529267,2018-11-08,f,NaN,Eixample,41.388619,2.168970,Entire home/apt
6696289,29529267,2018-11-07,f,NaN,Eixample,41.388619,2.168970,Entire home/apt

In [16]:
table_neighborhoods_test = table_neighborhoods.copy()

In [17]:
table_neighborhoods_test.room_type.unique()

array(['Private room', 'Entire home/apt', 'Shared room'], dtype=object)

In [18]:
table_neighborhoods_test.room_type[['Entire home/apt', 'Private room', 'Shared room']].value_count()

KeyError: "None of [Index(['Entire home/apt', 'Private room', 'Shared room'], dtype='object')] are in the [index]"

In [ ]:
table_neighborhoods_room_types_original.groupby('room_type').count()

## Data Wrangling

### formula to remove $ & transforming to float

In [ ]:
# float(table_neighborhoods.loc[400, 'adjusted_price'].split("$")[1])

In [25]:
table_neighborhoods_test['price_x']  = table_neighborhoods_test['price_x'].str.replace('$','')

In [26]:
table_neighborhoods_test['price_x']  = table_neighborhoods_test['price_x'].str.replace(',','')

In [27]:
table_neighborhoods_test['price_x'] = table_neighborhoods_test['price_x'].astype(float)

In [28]:
table_neighborhoods_test.nlargest(50, ['price_x'], keep='first')

,listing_id,date,available,price_x,neighbourhood_group,latitude,longitude,room_type
6640810,29498321,2019-09-10,t,11420.0,Sant Andreu,41.437127,2.187961,Entire home/apt
6640811,29498321,2019-09-09,t,11420.0,Sant Andreu,41.437127,2.187961,Entire home/apt
6640812,29498321,2019-09-08,t,11420.0,Sant Andreu,41.437127,2.187961,Entire home/apt
6640813,29498321,2019-09-07,t,11420.0,Sant Andreu,41.437127,2.187961,Entire home/apt
6640814,29498321,2019-09-06,t,11420.0,Sant Andreu,41.437127,2.187961,Entire home/apt
6640815,29498321,2019-09-05,t,11420.0,Sant Andreu,41.437127,2.187961,Entire home/apt
6640816,29498321,2019-09-04,t,11420.0,Sant Andreu,41.437127,2.187961,Entire home/apt
6640817,29498321,2019-09-03,t,11420.0,Sant Andreu,41.437127,2.187961,Entire home/apt
6640818,29498321,2019-09-02,t,11420.0,Sant Andreu,41.437127,2.187961,Entire home/apt
6640819,29498321,2019-09-01,t,11420.0,Sant Andreu,41.437127,2.187961,Entire home/apt
6640820,29498321,2019-08-31,t,11420.0,Sant Andreu,41.437127,2.187961,Entire home/apt
6640821,29498321,2019-08-30,t,11420.0,Sant Andreu,41.437127,2.187961,Entire home/apt
6640822,29498321,2019-08-29,t,11420.0,Sant Andreu,41.437127,2.187961,Entire home/apt
6640823,29498321,2019-08-28,t,11420.0,Sant Andreu,41.437127,2.187961,Entire home/apt
6640824,29498321,2019-08-27,t,11420.0,Sant Andreu,41.437127,2.187961,Entire home/apt
6640825,29498321,2019-08-26,t,11420.0,Sant Andreu,41.437127,2.187961,Entire home/apt
6640826,29498321,2019-08-25,t,11420.0,Sant Andreu,41.437127,2.187961,Entire home/apt
6640827,29498321,2019-08-24,t,11420.0,Sant Andreu,41.437127,2.187961,Entire home/apt
6640828,29498321,2019-08-23,t,11420.0,Sant Andreu,41.437127,2.187961,Entire home/apt
6640829,29498321,2019-08-22,t,11420.0,Sant Andreu,41.437127,2.187961,Entire home/apt
6640830,29498321,2019-08-21,t,11420.0,Sant Andreu,41.437127,2.187961,Entire home/apt
6640831,29498321,2019-08-20,t,11420.0,Sant Andreu,41.437127,2.187961,Entire home/apt
6640832,29498321,2019-08-19,t,11420.0,Sant Andreu,41.437127,2.187961,Entire home/apt
6640833,29498321,2019-08-18,t,11420.0,Sant Andreu,41.437127,2.187961,Entire home/apt
6640834,29498321,2019-08-17,t,11420.0,Sant Andreu,41.437127,2.187961,Entire home/apt
6640835,29498321,2019-08-16,t,11420.0,Sant Andreu,41.437127,2.187961,Entire home/apt
6640836,29498321,2019-08-15,t,11420.0,Sant Andreu,41.437127,2.187961,Entire home/apt
6640837,29498321,2019-08-14,t,11420.0,Sant Andreu,41.437127,2.187961,Entire home/apt
6640838,29498321,2019-08-13,t,11420.0,Sant Andreu,41.437127,2.187961,Entire home/apt
6640839,29498321,2019-08-12,t,11420.0,Sant Andreu,41.437127,2.187961,Entire home/apt
6640840,29498321,2019-08-11,t,11420.0,Sant Andreu,41.437127,2.187961,Entire home/apt
6640841,29498321,2019-08-10,t,11420.0,Sant Andreu,41.437127,2.187961,Entire home/apt
6640842,29498321,2019-08-09,t,11420.0,Sant Andreu,41.437127,2.187961,Entire home/apt
6640843,29498321,2019-08-08,t,11420.0,Sant Andreu,41.437127,2.187961,Entire home/apt
6640844,29498321,2019-08-07,t,11420.0,Sant Andreu,41.437127,2.187961,Entire home/apt
6640845,29498321,2019-08-06,t,11420.0,Sant Andreu,41.437127,2.187961,Entire home/apt
6640846,29498321,2019-08-05,t,11420.0,Sant Andreu,41.437127,2.187961,Entire home/apt
6640847,29498321,2019-08-04,t,11420.0,Sant Andreu,41.437127,2.187961,Entire home/apt
6640848,29498321,2019-08-03,t,11420.0,Sant Andreu,41.437127,2.187961,Entire home/apt
6640849,29498321,2019-08-02,t,11420.0,Sant Andreu,41.437127,2.187961,Entire home/apt
6640850,29498321,2019-08-01,t,11420.0,Sant Andreu,41.437127,2.187961,Entire home/apt
6640851,29498321,2019-07-31,t,11420.0,Sant Andreu,41.437127,2.187961,Entire home/apt
6640852,29498321,2019-07-30,t,11420.0,Sant Andreu,41.437127,2.187961,Entire home/apt
6640853,29498321,2019-07-29,t,11420.0,Sant Andreu,41.437127,2.187961,Entire home/apt
6640854,29498321,2019-07-28,t,11420.0,Sant Andreu,41.437127,2.187961,Entire home/apt
6640855,29498321,2019-07-27,t,11420.0,Sant Andreu,41.437127,2.187961,Entire home/apt
6640856,29498321,2019-07-26,t,11420.0,Sant Andreu,41.437127,2.187961,Entire home/apt
6640857,29498321,2019-07-25,t,11420.0,Sant Andreu,41.437127,2.187961,Entire home/apt
6640858,29498321,2019-07-24,t,11420.0,Sant Andreu,41.437127,2.187961,Entire home/apt
6640859,29498321,2019-07-23,t,11420.0,Sant Andreu,41.437127,2.187961,Entire home/apt

In [19]:
table_neighborhoods_test.head(20)

,listing_id,date,available,price_x,neighbourhood_group,latitude,longitude,room_type
0,74562,2019-11-06,t,$60.00,Ciutat Vella,41.38255,2.168365,Private room
1,74562,2019-11-05,t,$60.00,Ciutat Vella,41.38255,2.168365,Private room
2,74562,2019-11-04,t,$60.00,Ciutat Vella,41.38255,2.168365,Private room
3,74562,2019-11-03,t,$60.00,Ciutat Vella,41.38255,2.168365,Private room
4,74562,2019-11-02,t,$65.00,Ciutat Vella,41.38255,2.168365,Private room
5,74562,2019-11-01,t,$65.00,Ciutat Vella,41.38255,2.168365,Private room
6,74562,2019-10-31,t,$60.00,Ciutat Vella,41.38255,2.168365,Private room
7,74562,2019-10-30,t,$60.00,Ciutat Vella,41.38255,2.168365,Private room
8,74562,2019-10-29,t,$60.00,Ciutat Vella,41.38255,2.168365,Private room
9,74562,2019-10-28,t,$60.00,Ciutat Vella,41.38255,2.168365,Private room
10,74562,2019-10-27,t,$60.00,Ciutat Vella,41.38255,2.168365,Private room
11,74562,2019-10-26,t,$65.00,Ciutat Vella,41.38255,2.168365,Private room
12,74562,2019-10-25,t,$65.00,Ciutat Vella,41.38255,2.168365,Private room
13,74562,2019-10-24,t,$60.00,Ciutat Vella,41.38255,2.168365,Private room
14,74562,2019-10-23,t,$60.00,Ciutat Vella,41.38255,2.168365,Private room
15,74562,2019-10-22,t,$60.00,Ciutat Vella,41.38255,2.168365,Private room
16,74562,2019-10-21,t,$60.00,Ciutat Vella,41.38255,2.168365,Private room
17,74562,2019-10-20,t,$60.00,Ciutat Vella,41.38255,2.168365,Private room
18,74562,2019-10-19,t,$65.00,Ciutat Vella,41.38255,2.168365,Private room
19,74562,2019-10-18,t,$65.00,Ciutat Vella,41.38255,2.168365,Private room

In [20]:
table_neighborhoods_test.dtypes

listing_id               int64
date                    object
available               object
price_x                 object
neighbourhood_group     object
latitude               float64
longitude              float64
room_type               object
dtype: object

#### Exporting saved tables

In [26]:
table_neighborhoods_test.to_csv(r'D:\IronHack\IronHack_Classes\Week 4\AirBnB_project3\DataSets\vDef\'table_neighborhoods_objects.csv')

In [34]:
table_neighborhoods_room_types_original.to_csv(r'D:\IronHack\IronHack_Classes\Week 4\AirBnB_project3\DataSets\vDef\table_neighborhoods_room_types_original.csv')

In [28]:
# table_neighborhoods_test['adjusted_price'] = table_neighborhoods_test['adjusted_price'].apply(lambda x:float(table_neighborhoods_test.iloc['adjusted_price'].split("$")[1]))

TypeError: Cannot index by location index with a non-integer key

## Dividing Original DataFrame between neighbourhoods & Room types

In [37]:
df_entire_home = table_neighborhoods_test.copy()

In [39]:
filter_entire_home = df_entire_home['room_type'].str.contains('Entire home')

In [40]:
# use boolean conditional with .loc
df_entire_home = df_entire_home.loc[filter_entire_home ]

In [41]:
#Creating df_entire_home with only Entire Home Room Type
df_entire_home.head()

,listing_id,date,available,price_x,neighbourhood_group,latitude,longitude,room_type
1460,21601125,2018-10-17,f,NaN,Sant Martí,41.412407,2.225365,Entire home/apt
1461,21601125,2018-10-16,f,NaN,Sant Martí,41.412407,2.225365,Entire home/apt
1462,21601125,2018-10-15,f,NaN,Sant Martí,41.412407,2.225365,Entire home/apt
1463,21601125,2018-10-14,f,NaN,Sant Martí,41.412407,2.225365,Entire home/apt
1464,21601125,2018-10-13,f,NaN,Sant Martí,41.412407,2.225365,Entire home/apt

In [51]:
df_entire_home.drop(columns=['room_type'])

,listing_id,date,available,price_x,neighbourhood_group,latitude,longitude
0,29671890,2019-12-09,t,55.0,Sants-Montjuïc,41.369988,2.124774
1,29671890,2019-12-08,t,55.0,Sants-Montjuïc,41.369988,2.124774
2,29671890,2019-12-07,t,55.0,Sants-Montjuïc,41.369988,2.124774
3,29671890,2019-12-06,t,55.0,Sants-Montjuïc,41.369988,2.124774
4,29671890,2019-12-05,t,55.0,Sants-Montjuïc,41.369988,2.124774
...,...,...,...,...,...,...,...
6887180,30732856,2018-12-15,t,70.0,Eixample,41.392822,2.160387
6887181,30732856,2018-12-14,t,70.0,Eixample,41.392822,2.160387
6887182,30732856,2018-12-13,t,70.0,Eixample,41.392822,2.160387
6887183,30732856,2018-12-12,t,70.0,Eixample,41.392822,2.160387
6887184,30732856,2018-12-11,t,70.0,Eixample,41.392822,2.160387

In [43]:
df_entire_home_3000 = df_entire_home.loc[df_entire_home["price_x"] < 3000]

In [44]:
df_entire_home_3000.drop(columns='room_type', inplace=True)

c:\users\langl\appdata\local\programs\python\python38\lib\site-packages\pandas\core\frame.py:4110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

In [45]:
df_entire_home_3000

,listing_id,date,available,price_x,neighbourhood_group,latitude,longitude
1781,21601125,2017-12-26,t,25.0,Sant Martí,41.412407,2.225365
1782,21601125,2017-12-25,t,25.0,Sant Martí,41.412407,2.225365
1783,21601125,2017-12-24,t,25.0,Sant Martí,41.412407,2.225365
1784,21601125,2017-12-23,t,25.0,Sant Martí,41.412407,2.225365
1785,21601125,2017-12-22,t,25.0,Sant Martí,41.412407,2.225365
...,...,...,...,...,...,...,...
6707578,3477316,2018-07-03,t,85.0,Sant Martí,41.422400,2.206462
6707579,3477316,2017-12-08,t,120.0,Sant Martí,41.422400,2.206462
6707580,3477316,2017-12-07,t,75.0,Sant Martí,41.422400,2.206462
6707581,3477316,2017-12-06,t,75.0,Sant Martí,41.422400,2.206462
6707582,3477316,2017-12-05,t,75.0,Sant Martí,41.422400,2.206462

In [46]:
df_entire_home_3000.to_csv(r'D:\IronHack\IronHack_Classes\Week 4\AirBnB_project3\DataSets\vDef\2018\f_2018_under_3K€.csv')